"""Added Notification Model

Revision ID: 6c13ddd4032c
Revises: f671c7d3db84
Create Date: 2026-07-10 18:02:55.541434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c13ddd4032c'
down_revision = 'f671c7d3db84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('action_url', sa.String(length=255), nullable=True),
    sa.Column('reference_id', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_notification_id'), ['notification_id'], unique=True)

    with op.batch_alter_table('fraud_detection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fraud_detection_claim_id'))

    op.drop_table('fraud_detection')
    with op.batch_alter_table('pharmacies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pharmacies_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_pharmacies_pharmacy_id'))

    op.drop_table('pharmacies')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.alter_column('predicted_risk',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('risk_level',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'Not Predicted'"))
        batch_op.alter_column('duplicate_claim',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.alter_column('duplicate_claim',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('risk_level',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Not Predicted'"))
        batch_op.alter_column('predicted_risk',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    op.create_table('pharmacies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pharmacy_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('pharmacy_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('hospital_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('hospital_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('medicine_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('medicine_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=150), nullable=True),
    sa.Column('batch_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('quantity_in_stock', sa.INTEGER(), nullable=True),
    sa.Column('minimum_stock', sa.INTEGER(), nullable=True),
    sa.Column('unit_price', sa.FLOAT(), nullable=True),
    sa.Column('total_value', sa.FLOAT(), nullable=True),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('remarks', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medicine_code')
    )
    with op.batch_alter_table('pharmacies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pharmacies_pharmacy_id'), ['pharmacy_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_pharmacies_hospital_id'), ['hospital_id'], unique=False)

    op.create_table('fraud_detection',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('claim_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('hospital_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('disease', sa.VARCHAR(length=120), nullable=False),
    sa.Column('claim_amount', sa.FLOAT(), nullable=False),
    sa.Column('predicted_risk', sa.FLOAT(), nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('duplicate_claim', sa.BOOLEAN(), nullable=True),
    sa.Column('ai_remark', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fraud_detection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fraud_detection_claim_id'), ['claim_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_notification_id'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
