"""Initial Database

Revision ID: f671c7d3db84
Revises: 
Create Date: 2026-07-05 19:48:02.466946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f671c7d3db84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('disease', sa.String(length=150), nullable=True),
    sa.Column('insurance_provider', sa.String(length=150), nullable=True),
    sa.Column('insurance_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('pharmacies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.String(length=20), nullable=False),
    sa.Column('pharmacy_name', sa.String(length=150), nullable=False),
    sa.Column('hospital_id', sa.String(length=20), nullable=False),
    sa.Column('hospital_name', sa.String(length=150), nullable=False),
    sa.Column('medicine_name', sa.String(length=150), nullable=False),
    sa.Column('medicine_code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=True),
    sa.Column('minimum_stock', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medicine_code')
    )
    with op.batch_alter_table('pharmacies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pharmacies_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacies_pharmacy_id'), ['pharmacy_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('is_active_account', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.String(length=20), nullable=False),
    sa.Column('hospital_id', sa.String(length=20), nullable=False),
    sa.Column('hospital_name', sa.String(length=150), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=True),
    sa.Column('disease', sa.String(length=150), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('claim_amount', sa.Float(), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=False),
    sa.Column('treatment_cost', sa.Float(), nullable=False),
    sa.Column('claim_status', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('fraud_probability', sa.Float(), nullable=False),
    sa.Column('fraud_flag', sa.Boolean(), nullable=False),
    sa.Column('duplicate_claim', sa.Boolean(), nullable=False),
    sa.Column('ai_prediction', sa.String(length=50), nullable=True),
    sa.Column('reviewer', sa.String(length=120), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('submitted_date', sa.Date(), nullable=True),
    sa.Column('reviewed_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_claim_id'), ['claim_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_claims_patient_id'), ['patient_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.String(length=20), nullable=False),
    sa.Column('report_title', sa.String(length=200), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('generated_by', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('hospital_id', sa.String(length=20), nullable=False),
    sa.Column('hospital_name', sa.String(length=150), nullable=False),
    sa.Column('report_status', sa.String(length=50), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('fraud_probability', sa.Float(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_report_id'), ['report_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_report_id'))
        batch_op.drop_index(batch_op.f('ix_reports_patient_id'))

    op.drop_table('reports')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_patient_id'))
        batch_op.drop_index(batch_op.f('ix_claims_claim_id'))

    op.drop_table('claims')
    op.drop_table('users')
    with op.batch_alter_table('pharmacies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pharmacies_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_pharmacies_hospital_id'))

    op.drop_table('pharmacies')
    op.drop_table('patients')
    # ### end Alembic commands ###
